### ISSUE TITLE
Please provide Moodle 4.x monologo files (PNG+SVG) and lib.php function with FEATURE_MOD_PURPOSE

### ISSUE THREAD

**Issue by danowar2k** [streamingltd/MEDIAL-Moodle-Activity#14]
Moodle provides "monologos" in Moodle 4.x . Please create those files for consistency among activity icons. Also necessary: The function in lib.php with which the colors for the activity icon are determined.

**Comment by tim1mw** [comment]
The monologo png+svg files and function.php change have now been added to out private developement version and will be part of the next release pushed to git.
