### ISSUE TITLE
Legacy cron broken by Helix mod 

### ISSUE THREAD

**Issue by aspark21** [streamingltd/MEDIAL-Moodle-Activity#2]
We have a site with only the mod_helixmedia plugin installed. Due to the way the cron tasks are implemented in this plugin, it is causing our legacy cron task to fail because the cron for the activity is running the cron for the helixassign plugin.

```
Processing module function helixmedia_cron ...
... used 16852 dbqueries
... used 29.082170009613 seconds
Scheduled task failed: Legacy cron processing for plugins (core\task\legacy_plugin_cron_task),Table "assignsubmission_helixassign" does not exist
Backtrace:
* line 1521 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
* line 294 of /mod/helixmedia/lib.php: call to moodle_database->get_record()
* line 93 of /lib/classes/task/legacy_plugin_cron_task.php: call to helixmedia_cron()
* line 105 of /lib/cronlib.php: call to core\task\legacy_plugin_cron_task->execute()
* line 297 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 91 of /admin/tool/task/schedule_task.php: call to cron_run_single_task()
```

Should really split the cron tasks up between the plugins in the helix set. Also consider creating it's own scheduled task rather than relying on legacy cron task.

**Comment by aspark21** [comment]
Specifically to address this:
1)helixmedia_cron should be converted to a scheduled task
https://docs.moodle.org/dev/Task_API

2)The task needs to be moved into the relevant plugin
So [this ](https://github.com/streamingltd/MEDIAL-Moodle-Activity/blob/master/lib.php#L263-L306) should be in helixassign and/or helixfeedback 

N.B. Shouldn't [this](https://github.com/streamingltd/MEDIAL-Moodle-Activity/blob/master/lib.php#L289) be $feed_installed=true

Otherwise the dependency for helixassign & helixfeedback should be added as a $plugin->dependency in version.php

**Comment by tim1mw** [comment]
Sorry for the slow reply, we don't use the Github issues for bug reports so this isn't monitored.

Converting the cron to use the scheduled tasks is on my todo list. However, not having the other plugins installed shouldn't cause a crash here, the cron job tests to see if they are present before executing the code that I suspect is causing the problem, for some reason that code thinks the plugin is installed on your system so I'll look into that.

**Comment by tim1mw** [comment]
Cron jobs have been converted to scheduled tasks in the 2020011201 release, so this can now close.
