### ISSUE TITLE
Medial videos not working on Moodle App

### ISSUE THREAD

**Issue by martabotellerumedicina** [streamingltd/MEDIAL-Moodle-Activity#20]
When trying to display a Medial video  ([MEDIAL | Media Library Software | Moodle Video Plugin|https://www.medial.com/]) within a Medial Activity added on a Moodle course the following error message appears: 'Call to undefined function mod_helixmedia\output\external_format_text()'

 

Tested on: Moodle App 4.3.0 (Android)

 

Students can load Medial videos if inserted as a links and 'open in browser option' is enabled. Medial videos won't display inserted with the Medial button inside the ATO editor.

![Activity_Moodle](https://github.com/streamingltd/MEDIAL-Moodle-Activity/assets/123969057/bf4536d5-53e1-4692-9371-4498326d050e)
![ATO_editor](https://github.com/streamingltd/MEDIAL-Moodle-Activity/assets/123969057/a447d191-304e-4985-a2c2-3f54aa413d38)
![Error_screenshot](https://github.com/streamingltd/MEDIAL-Moodle-Activity/assets/123969057/c20cc49b-85b0-4ccc-bada-efc02f723061)

**Comment by izendegi** [comment]
Hi @martabotellerumedicina 

We've also seen that issue and just proposed the PR #21 that fixes it
