### ISSUE TITLE
failing unit test

### ISSUE THREAD

**Issue by aspark21** [streamingltd/MEDIAL-Moodle-Activity#3]
Moodle: 3.4.6
DB: MySQL
Medial version: master (54c3f13)

search_manager_testcase::test_search_areas
Unexpected debugging() call detected.
Debugging: Class 'core_search\area\base_activity' has been renamed for the autoloader and is now deprecated. Please use 'core_search\base_activity' instead.
* line 119 of /lib/classes/component.php: call to debugging()
* line ? of unknownfile: call to core_component::classloader()
* line 36 of /mod/helixmedia/classes/search/activity.php: call to spl_autoload_call()
* line 113 of /lib/classes/component.php: call to include_once()
* line ? of unknownfile: call to core_component::classloader()
* line ? of unknownfile: call to spl_autoload_call()
* line 945 of /lib/classes/component.php: call to class_exists()
* line 262 of /search/classes/manager.php: call to core_component::get_component_classes_in_namespace()
* line 83 of /search/tests/manager_test.php: call to core_search\manager::get_search_areas_list()
* line ? of unknownfile: call to search_manager_testcase->test_search_areas()
* line 1071 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to ReflectionMethod->invokeArgs()
* line 939 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 698 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 894 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 755 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 546 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 195 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->doRun()
* line 148 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 53 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()

/data/apache/moodle-vhosts/346phpu/lib/phpunit/classes/advanced_testcase.php:88

To re-run:
 vendor/bin/phpunit "search_manager_testcase" search/tests/manager_test.php

**Comment by aspark21** [comment]
As of Moodle 3.6 this results in a Fatal Error:

Fatal error: Class 'core_search\area\base_activity' not found in /path/to/moodle/mod/helixmedia/classes/search/activity.php on line 36

**Comment by tim1mw** [comment]
The search class problem should be fixed in the latest release.
